#!/usr/bin/env bash
:
#shellcheck disable=2034
{
	ports_api=1

	name="dillo"
	version="3.2.0"
	desc="Dillo — lightweight FLTK/X11 web browser (static, TLS via mbedTLS)"
	cpe23="cpe:2.3:a:dillo:dillo:${version}:*:*:*:*:*:*:*"

	source="https://github.com/dillo-browser/dillo/archive/refs/tags"
	archive_filename="v${version}.tar.gz"
	src_path="dillo-${version}/"

	size="1459110"
	sha256="4282e4bc0de229d23cd3e36dda81bba9267709c76d59d592c429d4532cf1d451"

	# Dillo is GPLv3. Ports/recipes MAY carry (L)GPL; only the Phoenix core repos
	# must stay GPL-free, and phoenix-rtos-ports is a ports repo, so this is fine.
	license="GPL-3.0-only"
	license_file="COPYING"

	conflicts=""
	# fltk transitively pulls xorg_libs + libpng + libjpeg + zlib; mbedtls provides
	# libmbedtls/libmbedx509/libmbedcrypto + mbedtls/*.h; libiconv provides iconv.h +
	# libiconv.a (real GNU libiconv 1.18). All land in PREFIX_H/PREFIX_A.
	depends="fltk mbedtls libiconv"

	supports="phoenix>=3.3"
}

p_prepare() {
	# Two source patches (see patches/):
	#   0001 renames Dillo's private `extern "C" strndup()` in dw/selection.cc out of
	#        the way — libphoenix exports a non-weak strndup -> "multiple definition"
	#        at link; the 4 call sites then resolve to libphoenix's strndup.
	#   0002 changes uint_t connect_ret_size -> socklen_t in src/IO/http.c — Phoenix
	#        getsockopt() writes a socklen_t (8 bytes LP64) through that pointer; the
	#        uint_t (4 bytes) is a real stack-overwrite correctness bug.
	b_port_apply_patches "${PREFIX_PORT_WORKDIR}"

	# The tarball ships configure.ac but NO generated configure. Run autoreconf once
	# (openvpn idiom). Modern autoconf knows the `aarch64-phoenix` triplet, so the
	# autoreconf-generated config.sub needs no phoenix patch (proven by openvpn).
	if [ ! -x "${PREFIX_PORT_WORKDIR}/configure" ]; then
		(cd "${PREFIX_PORT_WORKDIR}" && autoreconf -i -v -f)
	fi
	# iconv (Dillo's configure hard-requires <iconv.h> + iconv_open()) comes from
	# the real GNU libiconv 1.18 framework port (depends="libiconv"): iconv.h in
	# ${PREFIX_H}, libiconv.a in ${PREFIX_A}, -liconv in the link closure below.
}

p_build() {
	# Dillo drives its final link through `fltk-config --ldflags`, which emits only
	# `-lfltk -lpthread -lX11` — it OMITS the full static closure (image libs, the
	# xcb/Xau/Xdmcp closure, mbedtls, and the --start-group wrapping a static C++/X
	# cross-link needs). Point FLTK_CONFIG at a WRAPPER whose --ldflags emits the
	# complete grouped closure; --cflags/--cxxflags/--version delegate to the real
	# fltk-config the fltk port installed to ${PREFIX_PORT_INSTALL}/bin/fltk-config.
	# Generate it unconditionally and BEFORE configure — configure bakes the
	# --ldflags output into src/Makefile (@LIBFLTK_LIBS@); make never re-invokes it.
	local wrap="${PREFIX_PORT_WORKDIR}/phoenix-fltk-config"
	cat > "${wrap}" <<WRAPEOF
#!/bin/sh
# AUTO-GENERATED by dillo/port.def.sh — full static link closure for Dillo.
REAL="${PREFIX_PORT_INSTALL}/bin/fltk-config"
case " \$* " in
	*" --ldflags "*)
		printf '%s ' "-L${PREFIX_A}" "--sysroot=${PREFIX_SYSROOT}" "-L${PREFIX_SYSROOT}/lib"
		printf '%s ' "-Wl,--start-group" \\
		  "-lfltk_images" "-lfltk" "-lpng16" "-ljpeg" "-lz" "-liconv" \\
		  "-lX11" "-lxcb" "-lXau" "-lXdmcp" \\
		  "-lmbedtls" "-lmbedx509" "-lmbedcrypto" \\
		  "-lstdc++" "-lm" "-lphoenix" "-lc" \\
		  "-Wl,--end-group"
		echo
		;;
	*)
		exec "\$REAL" "\$@"
		;;
esac
WRAPEOF
	chmod +x "${wrap}"

	# GCC 14 promotes -Wincompatible-pointer-types / -Wint-conversion to hard
	# errors; demote to warnings so the build completes. Force-include the shim
	# (AI_* getaddrinfo hint macros). All headers/libs (fltk, X, image
	# codecs, mbedtls) live in PREFIX_H/PREFIX_A.
	local xcflags="${CFLAGS} -I${PREFIX_H} -include ${PREFIX_PORT}/dillo-phoenix-shim.h -O2 -Wno-error=incompatible-pointer-types -Wno-error=int-conversion"
	local xldflags="${CFLAGS} ${LDFLAGS} -L${PREFIX_A}"

	# Prepend the framework bin/ so Dillo's configure picks up the FRAMEWORK
	# libpng16-config (emitting the cross prefix) instead of the host's
	# /usr/bin/libpng16-config, which would leak host -I/usr/include / a mismatched
	# libpng version into the cross build.
	if [ ! -f "${PREFIX_PORT_WORKDIR}/config.status" ]; then
		(cd "${PREFIX_PORT_WORKDIR}" && PATH="${PREFIX_PORT_INSTALL}/bin:${PATH}" FLTK_CONFIG="${wrap}" ./configure \
			--host="${HOST}" --build=x86_64-pc-linux-gnu --prefix="${PREFIX_PORT_INSTALL}" \
			--enable-tls --disable-openssl --disable-webp \
			--with-jpeg-lib="${PREFIX_A}" --with-jpeg-inc="${PREFIX_H}" \
			CC="${CROSS}gcc" CXX="${CROSS}g++" AR="${CROSS}ar" RANLIB="${CROSS}ranlib" \
			CFLAGS="${xcflags}" CXXFLAGS="${xcflags}" CPPFLAGS="${xcflags}" LDFLAGS="${xldflags}" \
			PKG_CONFIG=/bin/false)
	fi

	make -C "${PREFIX_PORT_WORKDIR}"

	mkdir -p "${PREFIX_PROG_STRIPPED}"
	$STRIP -o "${PREFIX_PROG_STRIPPED}/dillo" "${PREFIX_PORT_WORKDIR}/src/dillo"
	b_install "${PREFIX_PROG_TO_INSTALL}/dillo" /bin
}
