: # SPDX-License-Identifier: BSD-3-Clause
{
	ports_api=1
	name="sed"
	version="4.10"
	desc="GNU stream editor for filtering and transforming text"
	cpe23="cpe:2.3:a:gnu:sed:${version}:*:*:*:*:*:*:*"
	source="https://ftp.gnu.org/gnu/sed/"
	archive_filename="sed-${version}.tar.xz"
	src_path="sed-${version}/"
	size="1732800"
	sha256="b8e72182b2ec96a3574e2998c47b7aaa64cc20ce000d8e9ac313cc07cecf28c7"
	license="GPL-3.0-or-later"
	license_file="COPYING"
	conflicts=""
	depends=""
	supports="phoenix>=3.3"
}

# GNU sed via its own autoconf + gnulib, same shape as the coreutils port.
# Phoenix patches (patches/):
#   0001 teaches gnulib's stdio internals (fseterr/fwriting) about Phoenix's
#        FILE struct. Both files dispatch on a libc's private FILE layout and
#        end in "#error Please port ... to your platform"; libphoenix provides
#        neither __fseterr nor __fwriting, so gnulib compiles both. The Phoenix
#        branches read struct _FILE {fd,flags,mode,bufeof,bufpos,bufsz,buffer,
#        lock} with F_WRITING = 1<<1 and F_ERROR = 1<<3 (libphoenix
#        include/stdio.h + stdio/file.c). Same idea as coreutils' patch 0002,
#        regenerated for sed 4.10's gnulib (which no longer ships
#        freadahead/freading/freadptr/fpending/freadseek, and does ship
#        fwriting, which coreutils' gnulib did not compile).
#   0002 renames sed's global `debug` flag to `sed_debug`: libphoenix exports
#        an un-namespaced global `debug` (the kernel debug-console syscall
#        wrapper in arch/aarch64/syscalls.S), so the static link hit
#        "multiple definition of `debug'". The --debug option is unaffected.
# coreutils' 0001 (gettime/settime rename) is NOT needed: sed 4.10's gnulib has
# no gettime.c/settime.c, so nothing collides with libphoenix.
#
# config.site supplies the cross ac_cv_* answers (shared verbatim with the
# coreutils port): when cross-compiling, configure otherwise mis-guesses many
# functions libphoenix actually has as "missing/broken" and pulls in gnulib
# replacements that then fail to build.

p_prepare() {
	b_port_apply_patches "${PREFIX_PORT_WORKDIR}"

	if [ ! -f "${PREFIX_PORT_WORKDIR}/Makefile" ]; then
		# -O2 is load-bearing: at -O0, GCC defines __NO_INLINE__, so gnulib's
		# gl_cv_c_inline_effective test fails, HAVE_INLINE stays undefined, and the
		# gnulib extern-inline helpers are neither inlined at call sites nor emitted
		# out-of-line -> undefined references at link.
		(cd "${PREFIX_PORT_WORKDIR}" && CONFIG_SITE="${PREFIX_PORT}/config.site" ./configure \
			--host="${HOST}" --build=x86_64-pc-linux-gnu --prefix="${PREFIX_PORT_INSTALL}" \
			CC="${HOST}-gcc" AR="${HOST}-ar" RANLIB="${HOST}-ranlib" \
			CFLAGS="${CFLAGS} -O2" LDFLAGS="${CFLAGS} ${LDFLAGS} -static" \
			--disable-nls --disable-acl --disable-xattr --without-selinux)
	fi
}

p_build() {
	local prog="${PREFIX_PORT_WORKDIR}/sed/sed"

	# A binary older than the libc it links is stale by the ABI contract (the
	# same test scripts/check-no-stale-binaries.sh uses): sed's Makefile does not
	# know about libphoenix.a, so a core rebuild leaves it untouched and older.
	# Drop it and let make relink; the objects are still current, so it is cheap.
	local libc_ref="${PREFIX_SYSROOT}/lib/libphoenix.a"
	if [ -f "${libc_ref}" ] && [ -f "${prog}" ] && [ "${libc_ref}" -nt "${prog}" ]; then
		echo "sed: binary older than libphoenix.a; relinking"
		rm -f "${prog}"
	fi

	# SUBDIRS=. keeps `all` in the top directory: sed's SUBDIRS is
	# "po . gnulib-tests", and neither the message catalogues (--disable-nls)
	# nor the gnulib test harness (never run on target) is wanted here.
	#
	# It has to be `all` and not the `sed/sed` target directly: automake only
	# builds BUILT_SOURCES (the ~40 generated gnulib headers, lib/wchar.h among
	# them) as a prerequisite of `all`. Asking for sed/sed instead lets the
	# generated headers race the objects that include them under -j, which
	# showed up as "implicit declaration of function 'mbszero'" in lib/
	# mbrtoc32.c -- a file that compiles fine once lib/wchar.h exists.
	#
	# A real compile or link failure must fail the port -- no `-k ... || true`
	# here; the man page is generated by build-aux/help2man's dummy-man stand-in
	# (configure picks it when it cannot run the cross binary), so `all` does not
	# need to execute anything we just built.
	make -C "${PREFIX_PORT_WORKDIR}" SUBDIRS=.

	"${CROSS}readelf" -h "${prog}" | grep -q 'AArch64' ||
		b_die "sed: ${prog} is not an AArch64 executable"

	mkdir -p "${PREFIX_PROG}" "${PREFIX_PROG_STRIPPED}"
	cp -a "${prog}" "${PREFIX_PROG}/sed"
	${STRIP} -o "${PREFIX_PROG_STRIPPED}/sed" "${PREFIX_PROG}/sed"
	b_install "${PREFIX_PROG_TO_INSTALL}/sed" /usr/bin
}
